"""
Compare real strokes against strokes generated by the trained model and the
fallback generator, using standard mouse-dynamics measures.

Usage:
    python -m algorithms.mouse_model.evaluate --data boun-mouse-dynamics-dataset.zip --window-filter browsing
    python -m algorithms.mouse_model.evaluate --data data/bmdd --plot eval.png   (needs matplotlib)

For every real stroke the generators are asked to make the same start->end
move, so the distributions are directly comparable. The KS column is the
two-sample Kolmogorov-Smirnov statistic vs. real data (0 = identical
distributions, 1 = completely different).
"""

import argparse
import os

import numpy as np
from scipy.stats import ks_2samp

from . import fallback
from .dataset import iter_sessions
from .strokes import segment_strokes, to_canonical

METRICS = ["duration", "efficiency", "peak_speed", "max_deviation", "overshoot", "n_points", "mean_dt"]


def stroke_metrics(points, times):
    """Kinematic summary of one stroke (points (n,2) px, times (n,) s)."""
    points = np.asarray(points, float)
    times = np.asarray(times, float)
    seg = np.hypot(*np.diff(points, axis=0).T)
    dt = np.clip(np.diff(times), 0.004, None)
    speed = seg / dt
    if len(speed) >= 3:  # light smoothing so single noisy samples don't dominate
        speed = np.convolve(speed, np.ones(3) / 3, mode="valid")
    canon, D, _ = to_canonical(points)
    return {
        "distance": D,
        "duration": times[-1],
        "efficiency": D / max(seg.sum(), 1e-9),          # 1 = perfectly straight
        "peak_speed": float(speed.max()) if len(speed) else 0.0,  # px/s
        "max_deviation": float(np.abs(canon[:, 1]).max()),  # sideways bulge / distance
        "overshoot": float(canon[:, 0].max() > 1.02),     # went past the target
        "n_points": len(points),
        "mean_dt": float(np.diff(times).mean()),
    }


def trajectory_to_arrays(start, traj):
    """Convert generator output [(x, y, dt), ...] to (points, times)."""
    pts = np.vstack([np.asarray(start, float)[None], np.array([(x, y) for x, y, _ in traj])])
    times = np.concatenate([[0.0], np.cumsum([dt for _, _, dt in traj])])
    return pts, times


def fitts_fit(rows):
    """Least-squares duration = a + b * log2(distance + 1)."""
    d = np.array([r["distance"] for r in rows])
    t = np.array([r["duration"] for r in rows])
    b, a = np.polyfit(np.log2(d + 1), t, 1)
    return a, b


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", default="auto", choices=["auto", "bmdd", "balabit"])
    ap.add_argument("--data", required=True)
    ap.add_argument("--model", default="models/mouse_mdn.npz")
    ap.add_argument("--split", default="test", help="files to evaluate on (falls back to all)")
    ap.add_argument("--n", type=int, default=500, help="number of real strokes to compare")
    ap.add_argument("--window-filter", default=None, help="BMDD: only strokes in this window category, e.g. browsing")
    ap.add_argument("--temperature", type=float, default=1.0)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--plot", default=None, help="save example trajectories + speed profiles to this PNG")
    ap.add_argument("--resample-hz", type=float, default=None,
                    help="fill generated strokes up to this polling rate, as playback does (e.g. 100)")
    args = ap.parse_args(argv)
    rng = np.random.default_rng(args.seed)

    def as_played(start, traj):
        if args.resample_hz:
            from algorithms.player import resample  # imported lazily: it pulls in the controller
            traj = resample(traj, start, args.resample_hz, rng=rng)
        return trajectory_to_arrays(start, traj)

    real = []
    for sess in iter_sessions(args.dataset, args.data, split=args.split, seed=args.seed):
        real.extend(segment_strokes(sess, window_filter=args.window_filter))
        if len(real) >= args.n:
            break
    real = real[:args.n]
    print(f"Evaluating on {len(real)} real strokes")

    model = None
    if os.path.exists(args.model):
        from .sampler import MouseModel
        model = MouseModel.load(args.model)
    else:
        print(f"(no model at {args.model} - comparing fallback only)")

    rows = {"real": [], "model": [], "fallback": []}
    examples = []
    failures = 0
    for s in real:
        start, end = s.points[0], s.points[-1]
        rows["real"].append(stroke_metrics(s.points, s.times))
        rows["fallback"].append(stroke_metrics(*as_played(start, fallback.generate(start, end, rng))))
        if model:
            traj = model.generate(start, end, rng, temperature=args.temperature)
            if traj is None:
                failures += 1
                continue
            m_pts, m_times = as_played(start, traj)
            rows["model"].append(stroke_metrics(m_pts, m_times))
            if len(examples) < 6:
                examples.append((s.points, s.times, m_pts, m_times))
    if model:
        print(f"Model failed to reach target on {failures}/{len(real)} strokes (fallback used at runtime)")

    # --- Table -----------------------------------------------------------------
    sources = [k for k in ("real", "model", "fallback") if rows[k]]
    print(f"\n{'metric':<14}" + "".join(f"{k + ' median [IQR]':>30}" for k in sources)
          + "".join(f"{'KS ' + k:>14}" for k in sources[1:]))
    for m in METRICS:
        line = f"{m:<14}"
        for k in sources:
            v = np.array([r[m] for r in rows[k]])
            q1, med, q3 = np.percentile(v, [25, 50, 75])
            line += f"{med:>12.3f} [{q1:.3f}, {q3:.3f}]".rjust(30)
        real_v = [r[m] for r in rows["real"]]
        for k in sources[1:]:
            line += f"{ks_2samp(real_v, [r[m] for r in rows[k]]).statistic:>14.3f}"
        print(line)

    print("\nDuration vs distance (Fitts-style: T = a + b*log2(D+1)):")
    for k in sources:
        a, b = fitts_fit(rows[k])
        print(f"  {k:<9} a = {a:.3f} s, b = {b:.3f} s/bit")

    if args.plot and examples:
        _plot(examples, args.plot)


def _plot(examples, path):
    """Save real vs generated trajectories and speed profiles side by side."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed - skipping plot")
        return
    fig, axes = plt.subplots(2, len(examples), figsize=(3 * len(examples), 6))
    for i, (rp, rt, mp, mt) in enumerate(examples):
        ax = axes[0, i]
        ax.plot(rp[:, 0], rp[:, 1], ".-", ms=2, label="real")
        ax.plot(mp[:, 0], mp[:, 1], ".-", ms=2, label="model")
        ax.invert_yaxis()
        ax.set_aspect("equal", "datalim")
        ax = axes[1, i]
        for pts, tms, lab in ((rp, rt, "real"), (mp, mt, "model")):
            sp = np.hypot(*np.diff(pts, axis=0).T) / np.clip(np.diff(tms), 0.004, None)
            ax.plot(tms[1:], sp, label=lab)
        ax.set_xlabel("s")
    axes[0, 0].legend()
    axes[1, 0].set_ylabel("speed px/s")
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    print("Saved plot to", path)


if __name__ == "__main__":
    main()
